[project]
name = "hbc-shona-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "The LazyCoder", email = "malvernbright.95@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "huggingface-hub>=1.32.0",
    "langchain>=1.4.1",
    "langchain-community>=0.4.2",
    "llama-cpp-python>=0.3.35",
    "uvicorn>=0.53.0",
]

[project.scripts]
hbc-shona-assistant = "hbc_shona_assistant:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
